{% set name = "sqlbag" %}
{% set version = "0.1.1617247075" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlbag-{{ version }}.tar.gz
  sha256: b9d7862c3b2030356d796ca872907962fd54704066978d7ae89383f5123366ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - packaging
    - python >={{ python_min }},<4.0
    - six
    - sqlalchemy

test:
  imports:
    - sqlbag
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/djrobstep/sqlbag
  summary: Various snippets of SQL-related boilerplate
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
